# lexicon.py

VISUAL_STYLES = {
    "Biomechanical Gothic": "fusing organic geometry with cold industrial frameworks, H.R. Giger influence",
    "Industrial Desolation": "brutalist concrete monolithic structures, rusted iron gears, abandoned mega factories",
    "Cybernetic Void": "pitch black obsidian machinery, exposed circuitry glowing with low energy states",
    "Dieselpunk Decay": "heavy riveted steel plates, billowing soot stacks, grease stained combustion engines",
    "Clockwork Obsidian": "intricate interlocking gold and dark glass gears, perpetual motion aesthetics",
    "Abyssal Automata": "subterranean deep sea machinery, pressurized brass hulls, barnacle encrusted pistons",
    "Necro Industrial": "skeletal mechanical structures, ribcage reinforcement pillars, calcified wiring lattices",
    "Pneumatic Brutalism": "massive raw concrete blocks interconnected by high pressure steam bypass valves",
    "Reliquary Core": "sacred technological shrines, gilded processing units, ornate filigree on server racks",
    "Xenomorphic Forge": "alien manufacturing pods growing semi organic tools, weeping hydraulic fluid",
    "Rusted Megastructure": "kilometers of decaying iron scaffolding, collapsed gantry cranes, weathered plating",
    "Cryo Mechanical": "frost covered cooling manifolds, liquid nitrogen vent lines, frozen control interfaces",
    "Singularity Lattice": "impossible geometric frames folding inward, gravity defying metallic rings",
    "Fossilized Factory": "petrified ancient machinery embedded in stone strata, mineralized cog systems",
    "Teslapunk Overdrive": "exposed vacuum tubes, spinning dynamos, erratic electrical discharge copper coils",
    "Nanite Swarm": "fluid metallic surfaces constantly shifts and reforming, microscopic particulate clouds",
    "Mummified Circuitry": "ancient processing units wrapped in degraded insulating linen, dust covered nodes",
    "Void Engine": "hollow starship components housing stable miniature black holes, anti matter conduits",
    "Warp Tech Baroque": "highly decorative gold leaf molding covering unstable dimensional phase drives",
    "Submerged Foundry": "underwater assembly lines, churning dark water currents, rust bubbling from welds"
}

LIGHTING_PROFILES = {
    "Chiaroscuro": "extreme contrasts between deep shadow and piercing directional light beams",
    "Volumetric Creep": "heavy atmospheric fog cutting through harsh, isolated amber spotlights",
    "Bioluminescent Decay": "faint, sickly green phosphorescence bleeding from mechanical joints",
    "Strobe Flicker": "erratic high intensity white flashes casting chaotic, hyper detailed shadows",
    "Solar Eclipse Flare": "silhouetted machinery rimmed by a blinding, corona style backlighting edge",
    "Plasma Arcing": "violent violet electrical discharges casting brief, brilliant exposures",
    "Cherenkov Radiation": "an eerie, deep underwater blue glow emanating from fuel rods and cooling pools",
    "Molten Glow": "incandescent orange light radiating upwards from channels of liquid metal",
    "Smog Filtered Dusk": "muted, diffused crimson sunlight struggling through thick industrial pollution",
    "Laser Grid": "sharp monochromatic ruby red geometric scanning lines cutting through the dark",
    "Monochromatic Stark": "clinical, cold overhead laboratory white light with absolute zero color warmth",
    "Flickering Filament": "weak, dying yellow incandescent bulbs pulsing rhythmically on exposed wires",
    "Void Eclipse": "an ominous absence of light where the subject absorbs ambient illumination",
    "Amber Emergency": "rotating industrial hazard beacons casting a rhythmic orange sweeping wash",
    "Neon Bleed": "corrupted magenta and cyan illumination reflecting off wet oil slicks",
    "Subterranean Dim": "minimal ambient light bounced off damp cavern walls and low hanging pipes",
    "Quantum Shimmer": "iridescent, micro shifting light waves that alter color based on angle of view",
    "Corrupted Prism": "refracted light broken into unnatural chromatic aberration patterns at the edges",
    "Event Horizon Shadow": "light visibly bending around the central heavy mass of the apparatus",
    "Sulfur Haze": "sickly volumetric yellow fog illuminated by hidden underfloor base lights"
}

MATERIAL_MODIFIERS = [
    "corroded brushed steel",
    "oil slicked titanium",
    "matte black polymer",
    "oxidized copper wiring",
    "pitted cast iron casting",
    "tempered obsidian glass",
    "brushed iridium alloy",
    "rusted corrugated tin panels",
    "skeletal bone porcelain inserts",
    "petrified carbon fiber weave",
    "glowing phosphor impregnated resin",
    "tarnished brass filigree plating",
    "scratched chrome trim",
    "vulcanized reinforced rubber hosing",
    "liquid mercury sheeting",
    "calcified limestone composite blocks",
    "raw structural rebar framing",
    "heat blistered exhaust alloy",
    "weathered volcanic basalt blocks",
    "synthetic leather insulation blankets"
]
